---
- hosts: "{{target}}"
  remote_user: vagrant
  sudo: True
  vars:
    graphite:
      version: master
      timezone: Europe/Paris
      workers: 4
      secret_key: 'ob3sow^ik#4q(k5*tgw&6j+osyr^@0jus$yd+-#^&^d#%yim1!'
      nginx_server_port: 8082 ## port on which you can access Graphite, port 80 is reserved for grafana, if you use 80 you won't be able to access graphite
      nginx_server_name: stats.mywebsite.dev
      nginx_htpasswd: 'admin:YWG41BPzVAkN6'
      nginx_enable_ssl: true
      nginx_server_port_ssl: 8083 ## port to use for SSL (443 is reserved for grafana)
      nginx_ssl_path: "/etc/nginx/ssl/grafana"
      nginx_ssl_cert: ssl_certif.pem
      nginx_ssl_key: ssl_certif.key

    carbon:
      host: 0.0.0.0
      ssl: no
    db_graphite:
      name: graphite
      user: graphite
      password: graphite

    grafana_version: 1.6.1
    grafana_nginx_listen: "{{target}}" # nginx listen address, `127.0.0.1` by default, you need to use the public ip with you want an external access
    grafana_nginx_server_name: stats.mywebsite.dev
    grafana_nginx_htpasswd: 'admin:YWG41BPzVAkN6'
    grafana_nginx_enable_ssl: true
    grafana_nginx_ssl_path: "/etc/nginx/ssl/grafana" ## Folder where the SSL files will be added, default to /etc/nginx/ssl
    grafana_nginx_ssl_cert: ssl_certif.pem
    grafana_nginx_ssl_key: ssl_certif.key

  roles:
    - common
    - python
    - supervisor
    - role: nginx
      nginx_sites: none
    - postgres
    - graphite
    - nodejs
    - statsd
    - elasticsearch
    - grafana

  tasks:
    - ufw: state=enabled policy=allow
    - ufw: logging=on
    #- ufw: rule=deny port=8125 proto=any
    #- ufw: rule=allow proto=any src=0.0.0.0 port=8125
